name: Jiaji Sun

repo_names:
  - On-Campus-Navigation-System-for-Disabled-Student

10-ux-ui-criticism:
  - https://vimeo.com/756194873

11-models-from-data:
  - https://github.com/philipsun-cu/On-Campus-Navigation-System-for-Disabled-Student/blob/main/navi/navi/navi/ContentView.swift#L17
